import Head from 'next/head'
import Header from '../components/Header'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Contact Company</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
    </div>
  )
}
export default Home