import Head from 'next/head'
import BackBoard from '../components/BackBoard'
import FrequentlyQuestionsCard from '../components/FrequentlyQuestionsCard'
import { Layout } from 'antd';
import 'antd/dist/antd.css';
import SideNav from '../components/SideNav';

const { Sider, Content } = Layout;

const Home = () => {
  return (
    <div>
      <Head>
        <title>Contact Company</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Sider>
          <SideNav />
        </Sider>
        <Content>
          <BackBoard>
            <FrequentlyQuestionsCard />
          </BackBoard>
        </Content>
      </Layout>
    </div>
  )
}
export default Home