import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contact Campany</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <div className="text-6xl"> てすと</div>
    </div>
  )
}
